import { toNano } from "@ton/core";

export const pigsMap = (t: any) => [
  {
    title: "Bronze Pig",
    code: 1,
    price: process.env.NEXT_PUBLIC_TESTNET ? 1 : 0.1,
    earnings: 117,
    capacity: 100,
    levels: 3,
    coverUrl: "/imgs/pigs/placeholder.png",
    iconUrl: "/pig_icons/BronzePig_icon.png",
    purchase: t("purchase"),
  },
  {
    title: "Silver Pig",
    code: 2,
    price: process.env.NEXT_PUBLIC_TESTNET ? 2 : 0.2,
    earnings: 32700,
    capacity: 250,
    levels: 7,
    coverUrl: "/imgs/pigs/bronze.png",
    iconUrl: "/pig_icons/SilverPig_icon.png",
    purchase: t("upgradeSilver"),
  },
  {
    title: "Gold Pig",
    code: 3,
    price: process.env.NEXT_PUBLIC_TESTNET ? 3 : 0.3,
    earnings: 5971510,
    capacity: 500,
    levels: 10,
    coverUrl: "/imgs/pigs/gold.png",
    iconUrl: "/pig_icons/GoldPig_icon.png",
    purchase: t("upgradeGold"),
  },
  {
    title: "Diamond Pig",
    code: 4,
    price: process.env.NEXT_PUBLIC_TESTNET ? 4 : 0.4,
    earnings: 106288200,
    capacity: 1000,
    levels: 11,
    coverUrl: "/imgs/pigs/diamond.png",
    iconUrl: "/pig_icons/DiamondPig_icon.png",
    purchase: t("upgradeDiamond"),
  },
];

const usdToTon = (usd: number, tonPrice: number) => (usd / tonPrice).toFixed(2);

export const pigsMapV2 = (t: any) => [ //TODO: fetch capacityInTon from pig_shop?
  {
    title: t?.("storePage.bronzePig") as string,
    code: 1,
    slots: 27,
    level: 3,
    price: process.env.NEXT_PUBLIC_TESTNET ? 0.1 : 4,
    // priceInTon: usdToTon(11, tonPrice),
    rawPriceInTon: process.env.NEXT_PUBLIC_TESTNET ? 0.1 : 4,
    earnings: 117,
    cover: "/imgs/pigs/bronze.png",
    capacity: 100,
    capacityInTon: "0.1",
  },
  {
    title: t?.("storePage.silverPig") as string,
    code: 2,
    slots: 147,
    level: 7,
    price: process.env.NEXT_PUBLIC_TESTNET ? 0.2 : 40,
    // priceInTon: usdToTon(100, tonPrice),
    rawPriceInTon: process.env.NEXT_PUBLIC_TESTNET ? 0.2 : 40,
    earnings: 32700,
    cover: "/imgs/pigs/silver.png",
    capacity: 250,
    capacityInTon: "0.25",
  },
  {
    title: t?.("storePage.goldPig") as string,
    code: 3,
    slots: 377,
    level: 10,
    price:  process.env.NEXT_PUBLIC_TESTNET ? 0.3 : 400,
    // priceInTon: usdToTon(1000, tonPrice),
    rawPriceInTon: process.env.NEXT_PUBLIC_TESTNET ? 0.3 : 400,
    earnings: 5971510,
    cover: "/imgs/pigs/gold.png",
    capacity: 500,
    capacityInTon: "0.5",
  },
  {
    title: t?.("storePage.diamondPig") as string,
    code: 4,
    slots: 1000,
    level: 11,
    price: process.env.NEXT_PUBLIC_TESTNET ? 0.4 : 4000,
    // priceInTon: usdToTon(10000, tonPrice),
    rawPriceInTon: process.env.NEXT_PUBLIC_TESTNET ? 0.4 : 4000,
    earnings: 106288200,
    cover: "/imgs/pigs/diamond.png",
    capacity: 1000,
    capacityInTon: "0.75",
  },
];
