export const pigsMap = (t: any) => [
  {
    title: "Bronze Pig",
    code: 1,
    price: 11,
    earnings: 117,
    capacity: 100,
    levels: 3,
    coverUrl: "/imgs/pigs/placeholder.png",
    iconUrl: "/pig_icons/BronzePig_icon.png",
    purchase: t("purchase"),
  },
  {
    title: "Silver Pig",
    code: 2,
    price: 100,
    earnings: 32700,
    capacity: 250,
    levels: 7,
    coverUrl: "/imgs/pigs/bronze.png",
    iconUrl: "/pig_icons/SilverPig_icon.png",
    purchase: t("upgradeSilver"),
  },
  {
    title: "Gold Pig",
    code: 3,
    price: 1000,
    earnings: 5971510,
    capacity: 500,
    levels: 10,
    coverUrl: "/imgs/pigs/gold.png",
    iconUrl: "/pig_icons/GoldPig_icon.png",
    purchase: t("upgradeGold"),
  },
  {
    title: "Diamond Pig",
    code: 4,
    price: 10000,
    earnings: 106288200,
    capacity: 1000,
    levels: 11,
    coverUrl: "/imgs/pigs/diamond.png",
    iconUrl: "/pig_icons/DiamondPig_icon.png",
    purchase: t("upgradeDiamond"),
  },
];
export const pigsPriceMap: Record<string, number> = {
  "1": 11,
  "2": 100,
  "3": 1000,
  "4": 10000,
};

export const pigsMapNew = (t: any) => [
  {
    title: "Bronze Pig",
    code: 1,
    slots: 27,
    level: 3,
    price: 11,
    earnings: 117,
  },
  {
    title: "Silver Pig",
    code: 2,
    slots: 147,
    level: 7,
    price: 100,
    earnings: 32700,
  },
  {
    title: "Gold Pig",
    code: 3,
    slots: 377,
    level: 10,
    price: 1000,
    earnings: 5971510,
  },
  {
    title: "Diamond Pig",
    code: 4,
    slots: 1000,
    level: 11,
    price: 10000,
    earnings: 106288200,
  },
];
