export const pigsMap = (t: any) => [
  {
    title: "Bronze Pig",
    code: 1,
    price: 11,
    earnings: 117,
    capacity: 100,
    levels: 3,
    coverUrl: "/imgs/pigs/placeholder.png",
    iconUrl: "/pig_icons/BronzePig_icon.png",
    purchase: t("purchase"),
  },
  {
    title: "Silver Pig",
    code: 2,
    price: 100,
    earnings: 32700,
    capacity: 250,
    levels: 7,
    coverUrl: "/imgs/pigs/bronze.png",
    iconUrl: "/pig_icons/SilverPig_icon.png",
    purchase: t("upgradeSilver"),
  },
  {
    title: "Gold Pig",
    code: 3,
    price: 1000,
    earnings: 5971510,
    capacity: 500,
    levels: 10,
    coverUrl: "/imgs/pigs/gold.png",
    iconUrl: "/pig_icons/GoldPig_icon.png",
    purchase: t("upgradeGold"),
  },
  {
    title: "Diamond Pig",
    code: 4,
    price: 10000,
    earnings: 106288200,
    capacity: 1000,
    levels: 11,
    coverUrl: "/imgs/pigs/diamond.png",
    iconUrl: "/pig_icons/DiamondPig_icon.png",
    purchase: t("upgradeDiamond"),
  },
];

const usdToTon = (usd: number, tonPrice: number) => (usd / tonPrice).toFixed(2);

export const pigsMapNew = (t: any, tonPrice: number) => [
  {
    title: t?.("storePage.bronzePig"),
    code: 1,
    slots: 27,
    level: 3,
    price: 11,
    priceInTon: usdToTon(11, tonPrice),
    earnings: 117,
    cover: "/imgs/pigs/bronze.png",
    capacity: 100,
    capacityInTon: usdToTon(100, tonPrice),
  },
  {
    title: t?.("storePage.silverPig"),
    code: 2,
    slots: 147,
    level: 7,
    price: 100,
    priceInTon: usdToTon(100, tonPrice),
    earnings: 32700,
    cover: "/imgs/pigs/silver.png",
    capacity: 250,
    capacityInTon: usdToTon(250, tonPrice),
  },
  {
    title: t?.("storePage.goldPig"),
    code: 3,
    slots: 377,
    level: 10,
    price: 1000,
    priceInTon: usdToTon(1000, tonPrice),
    earnings: 5971510,
    cover: "/imgs/pigs/gold.png",
    capacity: 500,
    capacityInTon: usdToTon(500, tonPrice),
  },
  {
    title: t?.("storePage.diamondPig"),
    code: 4,
    slots: 1000,
    level: 11,
    price: 10000,
    priceInTon: usdToTon(10000, tonPrice),
    earnings: 106288200,
    cover: "/imgs/pigs/diamond.png",
    capacity: 1000,
    capacityInTon: usdToTon(1000, tonPrice),
  },
];
